export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  ACTIVATION_REQUEST: "ACTIVATION_REQUEST",
  ACTIVATION_SUCCESS: "ACTIVATION_SUCCESS",
  ACTIVATION_FAILURE: "ACTIVATION_FAILURE",
  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
  RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",
  GET_ITEMS: "GET_ITEMS",
  ADD_ITEM: "ADD_ITEMS",
  DELETE_ITEM: "DELETE_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  ITEMS_LOADING: "ITEMS_LOADING",
  UPDATE_EMAIL: "UPDATE_EMAIL"
};

export const productConstants = {
  GET_ITEMS: "GET_ITEMS",
  ADD_ITEM: "ADD_ITEMS",
  DELETE_ITEM: "DELETE_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  ITEMS_LOADING: "ITEMS_LOADING",
  ADD_ITEM_FAILURE: "ADD_ITEMS_FAILURE",
  DELETE_ITEM_FAILURE: "DELETE_ITEM_FAILURE",
  UPDATE_ITEM_FAILURE: "UPDATE_ITEM_FAILURE",
};

export const categoryConstants = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",
  GET_CATEGORY_BY_SLUG_REQUEST: "GET_CATEGORY_BY_SLUG_REQUEST",
  GET_CATEGORY_BY_SLUG_SUCCESS: "GET_CATEGORY_BY_SLUG_SUCCESS",
  GET_CATEGORY_BY_SLUG_FAILURE: "GET_CATEGORY_BY_SLUG_FAILURE",
  UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",
  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
};

export const cartConstants = {
  CART_ADD_ITEM: "CART_ADD_ITEM",
  CART_REMOVE_ITEM: "CART_REMOVE_ITEM",
  CART_ADD_ONE: "CART_ADD_ONE",
  CART_REMOVE_ONE: "CART_REMOVE_ONE"
};

export const orderConstants = {
  GET_ALL_ORDERS: "GET_ALL_ORDERS"
}